DECLARE @DATE AS  DATE
DECLARE @NDAYS AS INT

SET @DATE = GETDATE()
SET @NDAYS = 5


DECLARE @STARTDATE INT = 0
DECLARE @COUNT     INT = 0
DECLARE @NEWDATE   DATE = DATEADD(DAY, 1, @DATE)

WHILE @COUNT < @NDAYS
    BEGIN
        IF DATEPART(WEEKDAY, @NEWDATE) NOT IN (1, 7) --AND @NEWDATE NOT IN ( SELECT DT_HOLIDAY FROM TB_HOLIDAYS ) 
            SET @COUNT += 1;

        SELECT @NEWDATE = DATEADD(DAY, 1, @NEWDATE), @STARTDATE += 1;

    END

SELECT DATEADD(DAY, @STARTDATE, @DATE)